### PR TITLE
Implement room temperature tracking

### PR DESCRIPTION
**Pull request by codehag**
This change also introduces some formating changes (sorry)

But otherwise, it is all about the feature described in reflector (https://github.com/tc39/Reflector/issues/328).

Demo:

Screen-Recording-2020-11-12-at-2

### CODE REVIEW

**Comment by codehag** [comment]
Here are them names as per (forgotten) request: 

Screen-Recording-2020-11-12-at-2(1)

**Comment by Jack-Works** [comment]
I'd like to have an 👀 emoji

**Comment by codehag** [comment]
Sure! we can add that. Out of curiosity, when you use this emoji, is it something like "No position but watching with interest" ? or does it have another meaning for you? I noticed it is quite popular with delegates from China.

**Comment by Jack-Works** [comment]
> "No position but watching with interest"

Yes, exactly that meaning for me

**Pull request merged**
